### ISSUE TITLE
tus断点上传后立刻下载异常

### ISSUE THREAD

**Issue by sumous** [sjqzhang/go-fastdfs#206]
通过tus客户端进行上传，完成后立刻进行下载，会报500.
```python
2020-05-26 14:14:09,325 - urllib3.connectionpool:393 - DEBUG - http://10.0.0.56:8080 "GET /group1/big/upload/dd52a98b9af8a37a19fb2546308d2933 HTTP/1.1" 500 19
Traceback (most recent call last):
  File ".\test.py", line 47, in <module>
    download_file(fdfs_url)
  File "Z:\Documents\code\project\src\utils.py", line 142, in download_file
    r.raise_for_status()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url:http://10.0.0.56:8080/group1/big/upload/dd52a98b9af8a37a19fb2546308d2933
```

做了大量测试，发现每次上传完后大概等5s左右才能下载。这5s内，访问链接 /group1/upload?md5=63ba076f2dbb0b89a62c649add8c61b7&output=json获取文件信息也是空的。

对本地文件进行分析后，发现data/fileserver.db/000001.log文件也是在上传完成后大概5s左右才有数据。问题应该在这里了，是正常的么？

**Comment by sjqzhang** [comment]
是正常的，文件越大越慢，会对文件进行转存,可以试一下回调
