### ISSUE TITLE
leveldb 损坏

### ISSUE THREAD

**Issue by cwocwo** [sjqzhang/go-fastdfs#222]
版本 1.3.2
启动时异常：
```
open db file /usr/local/go-fastdfs/data/data/fileserver.db fail,maybe has opening
panic: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000031]

goroutine 1 [running]:
main.NewServer(0xc0001822d0)
	/opt/go/src/fastdfs/fileserver.go:348 +0xbb3
main.init.0()
	/opt/go/src/fastdfs/fileserver.go:3307 +0x76a
```
查看`fileserver.db`下的 `MANIFEST-000031` 文件大小为`0`

**Comment by sjqzhang** [comment]
是异常退出引起的么？删掉data整个目录，重启就可以正常提供服务。

**Comment by cwocwo** [comment]
我们吧go-fastdfs运行在kubernetes中， 重启了其所在的节点多次。
删掉data整个目录，可以正常启动了。

这样操作会造成数据丢失吗？
