### ISSUE TITLE
首次启动无权限报错

### ISSUE THREAD

**Issue by vinsonzou** [sjqzhang/go-fastdfs#8]
在CentOS7中，首次启动报错如下
```
panic: open file path: conf/cfg.json error: open conf/cfg.json: permission denied


goroutine 1 [running]:
main.ParseConfig(0x99d8f6, 0xd)
	/root/fileserver.go:422 +0x76b
main.init.0()
	/root/fileserver.go:2801 +0x222
main.init()
	<autogenerated>:1 +0x12b
```

启动用户为普通账户，非root账户

解决方法也简单，首次启动时，生成的目录给属主有x权限即可，即
```
chmod u+x conf
chmod u+x files
```

上传文件不存在，也是由于目录权限导致
./files/default无权限导致

建议代码中所有os.mkdir权限全部改为0775

**Comment by sjqzhang** [comment]
775会不会有风险？者做成配置选项让大家自已决定

**Comment by vinsonzou** [comment]
> 775会不会有风险？者做成配置选项让大家自已决定

有风险可以改为770，这样只有程序运行账户有权限

**Comment by sjqzhang** [comment]
我先改为0775，请帮忙验证一下 v1.0.9

**Comment by vinsonzou** [comment]
已修复
